apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-1
  labels:
    run: my-app-1
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 80
  selector:
    run: my-app-1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-2
  labels:
    run: my-app-2
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 80
  selector:
    run: my-app-2
  type: NodePort