apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-1
spec:
  selector:
    matchLabels:
      run: my-app-1
  replicas: 1
  template:
    metadata:
      labels:
        run: my-app-1
    spec:
      containers:
      - name: my-app-1
        image: kogoon/hello-world:1.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
spec:
  selector:
    matchLabels:
      run: my-app-2
  replicas: 1
  template:
    metadata:
      labels:
        run: my-app-2
    spec:
      containers:
      - name: my-app-2
        image: kogoon/testnginx:0.1
        ports:
        - containerPort: 80