apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      run: my-app
  replicas: 1
  template:
    metadata:
      labels:
        run: my-app
    spec:
      containers:
      - name: my-app
        image: public.ecr.aws/x6q8k2h4/my-registry:2274e66f90777b3e3f05b81d07a872679f5d3982
        ports:
        - containerPort: 80