apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: prod
spec:
  selector:
    app: rollout-bluegreen
